(function () {
  'use strict';
  const C = window.MisamoCommunity, store = window.MisamoStore;
  const main = document.querySelector('main.content');
  if (!C || !main) return;
  const me = store.USER.id, pages = {}, drafts = new Map();
  let active = 'home', profileId = me, recipientId = '', sharedPostId = '', homeFilter = '전체', homeSort = 'latest', searchTab = 'posts';
  const e = (tag, cls, text) => { const n = document.createElement(tag); if (cls) n.className = cls; if (text !== undefined) n.textContent = text; return n; };
  const button = (text, action, cls = 'community-button') => { const n = e('button', cls, text); n.type = 'button'; if (action) n.addEventListener('click', action); return n; };
  const toastNode = e('div', 'community-toast'); toastNode.setAttribute('role', 'status'); toastNode.hidden = true; document.body.append(toastNode); let toastTimer;
  function toast(text) { toastNode.textContent = text; toastNode.hidden = false; clearTimeout(toastTimer); toastTimer = setTimeout(() => { toastNode.hidden = true; }, 6000); }
  function attempt(fn) { try { return fn(); } catch (error) { toast(error.message || '처리하지 못했습니다. 다시 시도해주세요.'); return null; } }
  function dialog(title, build) {
    document.querySelectorAll('.community-dialog[open]').forEach(n => n.close());
    const trigger = document.activeElement, d = e('dialog', 'community-dialog'), head = e('header'), h = e('h2', '', title), body = e('div', 'community-dialog-body');
    h.id = 'community-dialog-title'; d.setAttribute('aria-labelledby', h.id);
    const close = () => d.close(); head.append(h, button('닫기', close)); d.append(head, body); document.body.append(d);
    d.addEventListener('close', () => { d.remove(); if (trigger?.isConnected) trigger.focus({preventScroll:true}); });
    d.addEventListener('click', event => { if (event.target === d) { const r=d.getBoundingClientRect(); if (event.clientX<r.left || event.clientX>r.right || event.clientY<r.top || event.clientY>r.bottom) close(); } });
    build(body, close); d.showModal(); return d;
  }
  const titles = {search:'검색',following:'팔로잉',profile:'프로필',activity:'활동',messages:'메시지',topics:'주제별 모임',seminars:'교육 & 세미나',advisors:'전문가 상담',resources:'자료실',preferences:'내 관심 관리'};
  Object.entries(titles).forEach(([id,title]) => { const page=e('section','page-view community-page'); page.dataset.page=id; page.setAttribute('aria-label',title); page.append(e('h1','',title)); main.append(page); pages[id]=page; });
  function navigate(view, suffix = '') {
    window.misamoNavigate?.(view);
    if (suffix) history.replaceState(null, '', '#' + view + '/' + encodeURIComponent(suffix));
    window.scrollTo({top:0,behavior:'instant'});
  }
  function openProfile(id) { profileId=id || me; navigate('profile',profileId); renderProfile(); }
  function openPost(id) {
    const post = C.post(id);
    if (!post) return toast('삭제되었거나 찾을 수 없는 게시글입니다.');
    let card = [...document.querySelectorAll('.post-card[data-post-id]')].find(n => n.dataset.postId === id);
    if (!card && window.MisamoPosting?.renderPost) { window.MisamoPosting.renderPost(post); card = [...document.querySelectorAll('.post-card[data-post-id]')].find(n => n.dataset.postId === id); }
    if (card) {
      const link=card.querySelector('[data-reading-link]');
      if (link) { link.click(); return; }
    }
    dialog(post.title, body => { const text=e('div','community-full-text',post.bodyText || '본문이 없습니다.'); body.append(text,button('작성자 보기',()=>openProfile(post.authorId))); });
  }
  function openMessages(id, postId='') { recipientId=id || ''; sharedPostId=postId; navigate('messages'); renderMessages(); }
  function profileButton(id) { const p=C.profile(id); return button(p?.name || '미사모 회원',()=>openProfile(id),'community-author'); }
  function empty(container,text,action) { const n=e('div','community-empty',text); if(action)n.append(action); container.append(n); }
  function excerpt(text) { const p=String(text||'').split(/\n\s*\n/)[0]; if(p.length<=230)return p; const sentence=p.match(/^.{1,230}?[.!?。](?:\s|$)/);return sentence?sentence[0]:'긴 본문이 있습니다. 게시글을 열어 전체 내용을 읽어보세요.'; }
  function resultCard(post) {
    const card=e('article','community-result'); card.dataset.communityResult=post.id;
    const top=e('div','community-result-meta'); top.append(profileButton(post.authorId),e('span','',post.category || post.type || '커뮤니티 글'));
    const h=e('h2'); h.append(button(post.title,()=>openPost(post.id),'community-title-link'));
    card.append(top,h,e('p','',excerpt(post.bodyText)));
    const tags=e('div','community-tags'); (post.tags||[]).slice(0,6).forEach(tag=>tags.append(button('#'+tag,()=>search(tag),'community-chip'))); card.append(tags);
    const actions=e('div','community-result-actions'); const bookmark=button(store.getBookmarks().includes(post.id)?'저장 해제':'저장',()=>attempt(()=>{const saved=store.toggleBookmark(post.id);bookmark.textContent=saved?'저장 해제':'저장';bookmark.setAttribute('aria-pressed',String(saved));window.dispatchEvent(new CustomEvent('misamo:post-rendered'));}));bookmark.setAttribute('aria-pressed',String(store.getBookmarks().includes(post.id)));
    actions.append(button('본문·댓글 보기',()=>openPost(post.id)),bookmark);card.append(actions);return card;
  }
  function postsInto(container, posts) { container.replaceChildren(); if(!posts.length)return empty(container,'조건에 맞는 글이 없습니다. 다른 조건으로 찾아보세요.');posts.forEach(post=>container.append(resultCard(post))); }
  function peopleInto(container, profiles) {
    container.replaceChildren(); if(!profiles.length)return empty(container,'조건에 맞는 사람이 없습니다.');
    profiles.forEach(p=>{const item=e('article','community-person');const image=e('img');image.src=p.avatar || store.USER.avatar;image.alt='';const info=e('div');info.append(profileButton(p.id),e('p','',p.bio || p.industry || '창업 경험을 나누는 미사모 회원'));
      item.append(image,info);if(p.id!==me){const following=C.state().following.includes(p.id);const b=button(following?'팔로잉':'팔로우',()=>attempt(()=>C.toggleFollow(p.id)));b.setAttribute('aria-pressed',String(following)); item.append(b);}container.append(item);});
  }
  const searchPage=pages.search;
  searchPage.insertAdjacentHTML('beforeend',`<form class="community-search-form"><label class="community-query-label">검색어<input type="search" data-community-query placeholder="글, 사람, 자료를 찾아보세요" autocomplete="off"></label><button type="submit" class="community-button primary">검색</button></form><div class="community-tabs" aria-label="검색 대상"><button type="button" data-search-tab="posts" aria-pressed="true">글</button><button type="button" data-search-tab="people" aria-pressed="false">사람</button><button type="button" data-search-tab="resources" aria-pressed="false">자료</button></div><details class="community-filters"><summary>필터</summary><div class="community-filter-fields"><label>주제<select data-search-category><option value="">전체 주제</option><option>창업 준비</option><option>운영 노하우</option><option>마케팅</option><option>자금·세무</option><option>정부지원</option><option>네트워킹</option></select></label><label>업종<select data-search-industry><option value="">전체 업종</option><option>외식·카페</option><option>소매·유통</option><option>온라인·플랫폼</option><option>서비스</option><option>교육</option><option>기타</option></select></label><label>작성자<select data-search-author><option value="">모든 작성자</option></select></label><label>이후 날짜<input type="date" data-search-from></label><label>이전 날짜<input type="date" data-search-to></label><button type="button" data-clear-filters class="community-button">필터 초기화</button></div></details><div class="community-results-toolbar"><p role="status" data-search-status></p><label>정렬<select data-search-sort><option value="latest">최신순</option><option value="popular">인기순</option><option value="oldest">오래된순</option></select></label></div><div data-search-results class="community-results"></div>`);
  const query=searchPage.querySelector('[data-community-query]'), results=searchPage.querySelector('[data-search-results]');
  const filters={}; ['category','industry','author','from','to','sort'].forEach(key=>{filters[key]=searchPage.querySelector('[data-search-'+key+']');filters[key].addEventListener('change',()=>attempt(renderSearch));});
  C.profiles().forEach(p=>{const o=e('option','',p.name);o.value=p.id;filters.author.append(o);});
  const normalize=s=>String(s||'').normalize('NFKC').toLocaleLowerCase().replace(/#/g,'').trim();
  function matching(text) {return normalize(query.value).split(/\s+/).filter(Boolean).every(word=>normalize(text).includes(word));}
  const resources=[{id:'resource-checklist',title:'창업 준비 체크리스트',category:'창업 준비',bodyText:'공간, 메뉴, 운영 준비 항목을 정리하는 개발용 예시 체크리스트입니다.',content:'항목,상태,메모\n공간 동선 확인,미확인,\n메뉴 설명 작성,미확인,\n운영 일정 정리,미확인,\n준비물 확인,미확인,',filename:'misamo-checklist.csv'}, {id:'resource-budget',title:'카페 창업 비용 기록 양식',category:'자금·세무',bodyText:'직접 예상 금액을 입력해보는 개발용 예시 CSV 양식입니다.',content:'구분,항목,예상금액,확정금액,메모\n초기 준비,인테리어,,,\n초기 준비,장비,,,\n월 운영,임차료,,,\n월 운영,소모품,,,',filename:'misamo-budget.csv'}];
  function renderSearch() {
    searchPage.querySelectorAll('[data-search-tab]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.searchTab===searchTab)));
    Object.entries(filters).forEach(([key,n])=>{const supported=searchTab==='posts'||(searchTab==='people'&&['industry','author'].includes(key))||(searchTab==='resources'&&key==='category');n.disabled=!supported;n.closest('label').hidden=!supported;});
    if(searchTab==='posts' && filters.from.value && filters.to.value && filters.from.value>filters.to.value){results.replaceChildren();searchPage.querySelector('[data-search-status]').textContent='시작 날짜가 종료 날짜보다 늦습니다.';return;}
    let list;
    if(searchTab==='people') {list=C.profiles().filter(p=>matching(p.name+' '+p.bio+' '+p.industry) && (!filters.industry.value||p.industry===filters.industry.value)&&(!filters.author.value||p.id===filters.author.value));peopleInto(results,list);}
    else if(searchTab==='resources'){list=resources.filter(p=>matching(p.title+' '+p.bodyText)&&(!filters.category.value||p.category===filters.category.value));renderResources(results,list);const existing=C.posts().filter(p=>p.resource&&matching(p.title+' '+p.bodyText)&&(!filters.category.value||p.category===filters.category.value));if(existing.length&&!list.length)results.replaceChildren();existing.forEach(p=>results.append(resultCard(p)));list=list.concat(existing);}
    else {list=C.posts().filter(p=>matching([p.title,p.bodyText,p.author,p.type,p.category,p.industry,...(p.tags||[])].join(' '))&&(!filters.category.value||p.category===filters.category.value)&&(!filters.industry.value||p.industry===filters.industry.value)&&(!filters.author.value||p.authorId===filters.author.value)&&(!filters.from.value||String(p.createdAt).slice(0,10)>=filters.from.value)&&(!filters.to.value||String(p.createdAt).slice(0,10)<=filters.to.value));sortPosts(list,filters.sort.value);postsInto(results,list);}
    searchPage.querySelector('[data-search-status]').textContent=(query.value?'“'+query.value+'” · ':'')+list.length+'개 결과';
  }
  function sortPosts(list,sort){return list.sort((a,b)=>sort==='popular'?(store.getPostLike(b.id).count-store.getPostLike(a.id).count)||String(b.createdAt).localeCompare(String(a.createdAt)):sort==='oldest'?String(a.createdAt).localeCompare(String(b.createdAt)):String(b.createdAt).localeCompare(String(a.createdAt)));}
  function search(value, opts={}) {query.value=String(value||'').replace(/^#/,'');searchTab=opts.tab||'posts';if(opts.reset!==false)Object.entries(filters).forEach(([key,n])=>{if(key!=='sort')n.value='';});if(opts.category)filters.category.value=opts.category;navigate('search');attempt(renderSearch);}
  searchPage.querySelector('form').addEventListener('submit',event=>{event.preventDefault();attempt(renderSearch);});
  searchPage.querySelectorAll('[data-search-tab]').forEach(n=>n.addEventListener('click',()=>{searchTab=n.dataset.searchTab;attempt(renderSearch);}));
  searchPage.querySelector('[data-clear-filters]').addEventListener('click',()=>{Object.entries(filters).forEach(([key,n])=>n.value=key==='sort'?'latest':'');attempt(renderSearch);});
  document.querySelectorAll('.topbar input[type=search], .explore-search input[type=search]').forEach(input=>input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();search(input.value);}}));
  const topSearch=document.querySelector('.topbar .search'); if(topSearch)topSearch.append(button('검색',()=>search(topSearch.querySelector('input').value),'community-search-submit'));
  document.querySelector('.explore-search button')?.addEventListener('click',()=>search(document.querySelector('.explore-search input').value));
  function renderFollowing(){const p=pages.following;p.replaceChildren(e('h1','','팔로잉'),e('p','community-muted','팔로우한 사람들의 글을 최신순으로 모았습니다.'));const list=e('div');p.append(list);const following=C.state().following;const posts=C.posts().filter(post=>following.includes(post.authorId));if(posts.length)postsInto(list,sortPosts(posts,'latest'));else empty(list,'아직 팔로우한 사람의 글이 없습니다.',button('사람 찾기',()=>search('',{tab:'people'})));}
  function renderProfile(){const p=C.profile(profileId)||C.profile(me),page=pages.profile;profileId=p.id;page.replaceChildren(e('h1','','프로필'));const card=e('section','community-profile');const image=e('img');image.src=p.avatar||store.USER.avatar;image.alt='';const info=e('div');info.append(e('h2','',p.name),e('p','',p.bio||'아직 소개가 없습니다.'),e('p','community-muted',p.industry||''));const posts=C.posts().filter(post=>post.authorId===p.id);info.append(e('p','',`게시글 ${posts.length}개`));card.append(image,info);
    if(p.id===me)card.append(button('프로필 수정',()=>dialog('프로필 수정',(body,close)=>{const f=e('form');const name=e('input');name.value=p.name;name.maxLength=40;name.required=true;const bio=e('textarea');bio.value=p.bio||'';bio.maxLength=500;const industry=e('select');['','외식·카페','소매·유통','온라인·플랫폼','서비스','교육','기타'].forEach(v=>{const o=e('option','',v||'업종 선택 안 함');o.value=v;industry.append(o);});industry.value=p.industry||'';[['닉네임',name],['소개',bio],['업종',industry]].forEach(([title,input])=>{const l=e('label','',title);l.append(input);f.append(l);});const save=button('저장');save.type='submit';const error=e('p','community-error');error.setAttribute('role','alert');f.append(error,save);f.addEventListener('submit',event=>{event.preventDefault();try{C.updateProfile({name:name.value,bio:bio.value,industry:industry.value});close();}catch(err){error.textContent=err.message;}});body.append(f);})),button('내 관심 관리',()=>navigate('preferences')));
    else {const followed=C.state().following.includes(p.id);const b=button(followed?'팔로잉 · 취소':'팔로우',()=>attempt(()=>C.toggleFollow(p.id)));b.setAttribute('aria-pressed',String(followed));card.append(b,button('메시지',()=>openMessages(p.id)));} page.append(card,e('h2','','작성한 글'));const list=e('div');page.append(list);postsInto(list,sortPosts(posts,'latest'));}
  function renderActivity(){const page=pages.activity;page.replaceChildren(e('h1','','활동'),e('p','community-muted','현재 브라우저에서 기록한 활동입니다. 외부 회원의 실시간 알림은 아직 연결되지 않았습니다.'));const state=C.state();if(!state.activity.length)return empty(page,'아직 기록된 활동이 없습니다.');state.activity.slice().forEach(item=>{const row=e('article','community-activity');row.classList.toggle('unread',!item.read);row.append(e('p','',item.text||'활동 기록'),e('small','',new Date(item.createdAt).toLocaleString('ko-KR')));if(item.postId&&C.post(item.postId))row.append(button('관련 글 보기',()=>{attempt(()=>C.markRead(item.id));openPost(item.postId);}));if(!item.read)row.append(button('읽음으로 표시',()=>attempt(()=>C.markRead(item.id))));page.append(row);});}
  function renderMessages(){const page=pages.messages;const old=page.querySelector('textarea');if(old&&page.dataset.recipient)drafts.set(page.dataset.recipient,old.value);page.dataset.recipient=recipientId;
    page.replaceChildren(e('h1','','메시지'),e('p','community-local-note','로컬 시제품 · 이 브라우저에만 보관되며 실제 상대방에게 전송되지 않습니다.'));
    const state=C.state(),people=C.profiles().filter(p=>p.id!==me&&!state.blocked.includes(p.id));const chooser=e('section','community-recipient-picker');const label=e('label','','받는 사람 검색');const field=e('input');field.type='search';field.placeholder='닉네임으로 찾기';label.append(field);const choices=e('div','community-recipient-list');chooser.append(label,choices);page.append(chooser);
    const drawPeople=()=>{choices.replaceChildren();people.filter(p=>normalize(p.name).includes(normalize(field.value))).forEach(p=>{const b=button(p.name,()=>openMessages(p.id,sharedPostId));b.setAttribute('aria-pressed',String(p.id===recipientId));choices.append(b);});};field.addEventListener('input',drawPeople);drawPeople();
    if(!recipientId)return empty(page,'대화할 사람을 선택해주세요.');const person=people.find(p=>p.id===recipientId);if(!person)return empty(page,'차단되었거나 찾을 수 없는 사용자입니다.');page.append(e('h2','',person.name+'에게 남긴 메시지'));
    const list=e('div','community-message-list');const messages=state.messages.filter(m=>m.recipientId===recipientId).slice().reverse();if(!messages.length)empty(list,'아직 보관한 메시지가 없습니다.');messages.forEach(m=>{const row=e('article','community-message');row.append(e('p','',m.text),e('small','','로컬 보관 · '+new Date(m.createdAt).toLocaleString('ko-KR')));if(m.postId&&C.post(m.postId))row.append(button('공유한 글 보기',()=>openPost(m.postId)));list.append(row);});page.append(list);
    const form=e('form','community-message-form'),input=e('textarea');input.setAttribute('aria-label','메시지 내용');input.placeholder='질문이나 공유할 내용을 입력해주세요';input.maxLength=4000;input.required=true;input.value=drafts.get(recipientId)||'';input.addEventListener('input',()=>drafts.set(recipientId,input.value));const error=e('p','community-error');error.setAttribute('role','alert');form.append(input);if(sharedPostId&&C.post(sharedPostId))form.append(e('p','community-share-reference','함께 보관할 글: '+C.post(sharedPostId).title));const submit=button('대화에 보관');submit.type='submit';form.append(error,submit);form.addEventListener('submit',event=>{event.preventDefault();try{const text=input.value;C.sendMessage(recipientId,text,sharedPostId);drafts.delete(recipientId);page.querySelector("textarea").value='';sharedPostId='';renderMessages();}catch(err){error.textContent=err.message;}});page.append(form);}
  const seminars=[{id:'seminar-plan',title:'사업계획서 구성 연습',description:'문제 정의, 고객, 운영 계획을 순서대로 정리하는 예시 세미나입니다.',meta:'온라인 · 일정 미정 · 개발용 예시'}, {id:'seminar-marketing',title:'우리 가게 소개 글 작성 모임',description:'소개 글을 함께 읽고 문장과 사진의 흐름을 살펴보는 예시 모임입니다.',meta:'온라인 · 일정 미정 · 개발용 예시'}];
  const advisors=[{id:'advisor-start',title:'창업 준비 상담',description:'준비 단계와 궁금한 점을 정리해보는 상담 접수 화면입니다.',meta:'창업 준비 · 개발용 예시'}, {id:'advisor-brand',title:'가게 소개·마케팅 상담',description:'브랜드 소개, 사진, 고객에게 전할 이야기에 관한 상담 접수 화면입니다.',meta:'마케팅 · 개발용 예시'}];
  function serviceDetail(service){dialog(service.title,(body,close)=>{body.append(e('p','',service.description),e('p','community-muted',service.meta),e('p','community-local-note','실제 행사·상담 신청은 전송되지 않습니다. 현재 브라우저의 신청 내역에 저장합니다.'));const existing=C.state().registrations.find(r=>r.serviceId===service.id);if(existing){body.append(e('p','','신청 내역에 저장되어 있습니다.'),button('신청 취소',()=>attempt(()=>{C.cancelRegistration(service.id);close();})));return;}
      const form=e('form'),label=e('label','','궁금한 점 (선택)'),input=e('textarea');input.maxLength=2000;label.append(input);const error=e('p','community-error');error.setAttribute('role','alert');const save=button('신청 내역에 저장');save.type='submit';form.append(label,error,save);form.addEventListener('submit',event=>{event.preventDefault();try{C.register(service.id,input.value);body.replaceChildren(e('h3','','신청 내역에 저장했습니다'),e('p','','내 활동과 이 화면에서 신청 기록을 확인할 수 있습니다.'),button('닫기',close));}catch(err){error.textContent=err.message;}});body.append(form);});}
  function renderServices(kind){const page=pages[kind],services=kind==='seminars'?seminars:advisors;page.replaceChildren(e('h1','',titles[kind]),e('p','community-muted','관심 있는 항목의 상세 내용과 신청 내역을 확인해보세요.'));services.forEach(service=>{const card=e('article','community-result');card.append(e('h2','',service.title),e('p','',service.description),e('small','',service.meta),button('상세·신청 보기',()=>serviceDetail(service)));const r=C.state().registrations.find(r=>r.serviceId===service.id);if(r)card.append(e('p','community-success','신청 내역에 저장됨 · '+new Date(r.createdAt).toLocaleDateString('ko-KR')));page.append(card);});}
  function resourceDetail(resource){dialog(resource.title,body=>{body.append(e('p','',resource.bodyText),e('pre','community-resource-preview',resource.content));const a=e('a','community-button','CSV 양식 다운로드');const blob=new Blob(['\uFEFF'+resource.content],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);a.href=url;a.download=resource.filename;body.append(a);body.closest('dialog').addEventListener('close',()=>URL.revokeObjectURL(url),{once:true});});}
  function renderResources(container,list=resources){container.replaceChildren();if(!list.length)return empty(container,'조건에 맞는 자료가 없습니다.');list.forEach(r=>{const row=e('article','community-result');row.append(e('h2','',r.title),e('p','',r.bodyText),button('미리보기·다운로드',()=>resourceDetail(r)));container.append(row);});}
  function renderTopics(){const page=pages.topics;page.replaceChildren(e('h1','','주제별 모임'),e('p','community-muted','창업 단계와 관심 주제로 글을 찾아보세요.'));const grid=e('div','community-topic-grid');['창업 준비','운영 노하우','마케팅','자금·세무','정부지원','네트워킹'].forEach(topic=>grid.append(button(topic,()=>search('',{category:topic}),'community-topic')));page.append(grid,button('사람들과 연결하기',()=>search('',{tab:'people'})));}
  function renderPreferences(){const page=pages.preferences,state=C.state();page.replaceChildren(e('h1','','내 관심 관리'),e('p','community-muted','숨긴 글, 일시 숨긴 사람, 차단과 즐겨찾기를 관리합니다.'));
    const section=(title,ids,resolve,restore)=>{const box=e('section','community-settings-group');box.append(e('h2','',title));if(!ids.length)box.append(e('p','community-muted','등록된 항목이 없습니다.'));ids.forEach(id=>{const row=e('div','community-setting-row');row.append(e('span','',resolve(id)),button('해제',()=>attempt(()=>restore(id))));box.append(row);});page.append(box);};
    section('숨긴 글',state.hidden,id=>C.post(id)?.title||'게시글',id=>C.restorePost(id));section('30일 소식 숨기기',Object.keys(state.snoozed),id=>C.profile(id)?.name||'회원',id=>C.unsnoozeAuthor(id));section('차단한 사람',state.blocked,id=>C.profile(id)?.name||'회원',id=>C.unblockAuthor(id));section('즐겨찾는 사람',state.favorites,id=>C.profile(id)?.name||'회원',id=>C.toggleFavorite(id));section('삭제한 내 글',state.deleted,id=>state.edits[id]?.title||'삭제한 게시글',id=>C.restoreDeleted(id));
    const reports=e('section','community-settings-group');reports.append(e('h2','','신고 기록'),e('p','community-muted','신고는 로컬 테스트 기록입니다. 운영자에게 전송되지 않았습니다.'));state.reports.forEach(r=>reports.append(e('p','',(C.post(r.postId)?.title||'게시글')+' · '+r.reason)));page.append(reports);}
  const feed=document.querySelector('[data-page="home"]'); const filterNav=feed.querySelector('[aria-label="피드 필터"]');
  function categoryMatch(post){if(homeFilter==='전체')return true;if(homeFilter==='창업 정보')return ['정보 공유','지원사업'].includes(post.type)||post.id==='demo-cafe'||post.id==='demo-support';if(homeFilter==='컨설팅 후기')return /컨설팅|후기/.test(post.type+' '+post.title);if(homeFilter==='세미나')return /세미나|교육|모임/.test(post.type+' '+post.category+' '+post.title);if(homeFilter==='네트워킹')return post.category==='네트워킹';return post.type==='질문';}
  const homeEmpty=e('div','community-empty','조건에 맞는 글이 없습니다. 다른 주제나 전체를 선택해보세요.');homeEmpty.hidden=true;feed.querySelector(".feed-panel").append(homeEmpty);
  function applyHome(){const available=new Map(C.posts().map(post=>[post.id,post]));const cards=[...feed.querySelectorAll('.post-card[data-post-id]')];let count=0;cards.forEach(card=>{const p=available.get(card.dataset.postId);const visible=!!p&&categoryMatch(p);card.classList.toggle('community-filtered',!visible);if(visible)count++;});homeEmpty.hidden=count>0||document.body.classList.contains('is-reading-post');if(homeSort!=='latest'||homeSortingRequested){const sorted=sortPosts(cards.map(card=>available.get(card.dataset.postId)).filter(Boolean),homeSort);sorted.forEach(p=>{const card=cards.find(n=>n.dataset.postId===p.id);homeEmpty.before(card);});}}
  let homeSortingRequested=false;
  filterNav?.querySelectorAll('button').forEach(b=>{b.setAttribute('aria-pressed',String(b.textContent.trim()==='전체'));b.addEventListener('click',()=>{homeFilter=b.textContent.trim();filterNav.querySelectorAll('button').forEach(n=>{n.classList.toggle('active',n===b);n.setAttribute('aria-pressed',String(n===b));});attempt(applyHome);});});
  const oldSort=feed.querySelector('.sort-button');if(oldSort){const label=e('label','community-home-sort','정렬');const select=e('select');select.setAttribute('aria-label','홈 게시글 정렬');[['latest','최신순'],['popular','인기순'],['oldest','오래된순']].forEach(([value,text])=>{const o=e('option','',text);o.value=value;select.append(o);});label.append(select);oldSort.replaceWith(label);select.addEventListener('change',()=>{homeSort=select.value;homeSortingRequested=true;attempt(applyHome);});}
  function linkView(node,view,label){node.setAttribute('data-view-link','');node.dataset.viewTarget=view;if(node.tagName==='A')node.href='#'+view;if(label){const span=node.querySelector('span');if(span)span.textContent=label;else node.textContent=label;}}
  document.querySelectorAll('.side-nav a').forEach(a=>{const text=a.textContent.trim();if(text==='피드')linkView(a,'following','팔로잉');if(text==='메시지')linkView(a,'messages');if(text==='알림')linkView(a,'activity');});
  document.querySelectorAll('.mobile-nav a').forEach(a=>{if(a.textContent.trim()==='알림')linkView(a,'activity');if(a.textContent.trim()==='프로필'){linkView(a,'profile');a.addEventListener('click',()=>{profileId=me;});}});
  document.querySelector('.top-actions [aria-label="알림"]')?.addEventListener('click',()=>navigate('activity'));document.querySelector('.top-actions [aria-label="보내기"]')?.addEventListener('click',()=>openMessages());document.querySelector('[aria-label="프로필 메뉴"]')?.addEventListener('click',()=>dialog('내 메뉴',(body,close)=>{[['내 프로필',()=>openProfile(me)],['저장한 콘텐츠',()=>navigate('saved')],['관심·숨김 관리',()=>navigate('preferences')],['내 활동',()=>navigate('activity')]].filter(([label]) => !window.matchMedia?.('(max-width: 980px)').matches || !['저장한 콘텐츠','내 활동'].includes(label)).forEach(([label,fn])=>body.append(button(label,()=>{close();fn();})));}));
  const menuViews={'창업 정보':'topics','컨설팅 서비스':'advisors','교육 & 세미나':'seminars','네트워킹':'topics','자료실':'resources'};
  document.querySelectorAll('.menu-group a').forEach(a=>{const text=a.textContent.trim();if(menuViews[text])linkView(a,menuViews[text]);else if(text==='성공 사례')a.addEventListener('click',event=>{event.preventDefault();search('성공');});});
  document.querySelectorAll('.consult-card').forEach(a=>linkView(a,'advisors'));
  document.querySelectorAll('.story-card').forEach((card,i)=>{const label=card.querySelector('p')?.textContent||'';const handler=()=>{if(i===0)navigate('write');else if(/세미나/.test(label))navigate('seminars');else if(/네트워킹/.test(label))navigate('topics');else search(/자유/.test(label)?'질문':label.replace('창업 꿀팁','창업').replace('컨설팅 후기','컨설팅'));};card.tabIndex=0;card.setAttribute('role','button');card.setAttribute('aria-label',i===0?'내 소식 작성':label+' 보기');card.addEventListener('click',handler);card.addEventListener('keydown',ev=>{if(ev.target===card&&['Enter',' '].includes(ev.key)){ev.preventDefault();handler();}});const child=card.querySelector('button');if(child){child.addEventListener('click',ev=>{ev.stopPropagation();handler();});}});
  document.querySelectorAll('.keyword-row span, .category-grid button').forEach(n=>{if(n.tagName!=='BUTTON'){n.tabIndex=0;n.setAttribute('role','button');}const go=()=>{const term=n.textContent.replace(/#/g,'').trim();if(term==='더보기')navigate('topics');else search(term);};n.addEventListener('click',go);n.addEventListener('keydown',ev=>{if(n.tagName!=='BUTTON'&&['Enter',' '].includes(ev.key)){ev.preventDefault();go();}});});
  document.addEventListener('click',event=>{const tag=event.target.closest('.post-card .tags span');if(tag)search(tag.textContent);});
  function hydrateTags(){document.querySelectorAll('.post-card .tags span').forEach(tag=>{if(tag.dataset.communityTag)return;tag.dataset.communityTag='';tag.tabIndex=0;tag.setAttribute('role','button');tag.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();search(tag.textContent);}});});}
  document.querySelectorAll('.right-rail button, .sidebar .promo-card button, .saved-consult button').forEach(b=>{const text=b.textContent.trim();if(/프로필 보기/.test(text))b.addEventListener('click',()=>openProfile(me));else if(/전문가|상담/.test(text))b.addEventListener('click',()=>navigate('advisors'));else if(/네트워킹/.test(text))b.addEventListener('click',()=>navigate('topics'));else if(/소개 보기|가이드 보기/.test(text))b.addEventListener('click',()=>dialog('미사모 이용 안내',body=>body.append(e('p','','창업 경험을 글로 나누고, 관심 있는 사람을 팔로우하고, 필요한 콘텐츠를 저장해보세요.'),e('p','','현재 개발 버전의 개인 활동은 이 브라우저에 저장됩니다.'))));});
  document.querySelectorAll('.schedule-list, .schedule-card').forEach(n=>n.querySelectorAll('a').forEach(a=>linkView(a,'seminars')));
  document.querySelectorAll('.resource-strip article').forEach((n,i)=>{n.tabIndex=0;n.setAttribute('role','button');const go=()=>resourceDetail(resources[i%resources.length]);n.addEventListener('click',go);n.addEventListener('keydown',ev=>{if(['Enter',' '].includes(ev.key)){ev.preventDefault();go();}});});
  function refreshRail(){
    const state=C.state(),p=C.profile(me),stats=document.querySelectorAll('.profile-card .stats dt');
    if(stats.length===3){stats[0].textContent=C.posts().filter(post=>post.authorId===me).length;stats[1].textContent='—';stats[1].title='회원 서버 연결 전';stats[2].textContent=state.following.length;}
    const name=document.querySelector('.profile-card .profile-row strong');if(name)name.textContent=p.name;
    const popular=document.querySelector('.popular-card ol');if(popular){popular.replaceChildren();sortPosts(C.posts(),'popular').slice(0,4).forEach((post,i)=>{const row=e('li');row.append(e('b','',String(i+1)),button(post.title,()=>openPost(post.id),'community-title-link'));popular.append(row);});}
  }
  document.querySelector('.popular-card header a')?.addEventListener('click',event=>{event.preventDefault();search('');filters.sort.value='popular';renderSearch();});
  document.querySelectorAll('.schedule-card article').forEach((row,i)=>{const service=seminars[i];if(!service){row.remove();return;}row.replaceChildren(e('div','',service.title),button('상세 보기',()=>serviceDetail(service)));});
  const scheduleTitle=document.querySelector('.schedule-card h2');if(scheduleTitle)scheduleTitle.textContent='교육·모임 둘러보기';
  function refresh(){attempt(()=>{hydrateTags();applyHome();refreshRail();const state=C.state();const badge=document.querySelector('.top-actions .has-badge span');if(badge){const unread=state.activity.filter(a=>!a.read).length;badge.textContent=String(unread);badge.hidden=!unread;}if(active==='search')renderSearch();else if(active==='following')renderFollowing();else if(active==='profile')renderProfile();else if(active==='activity')renderActivity();else if(active==='messages')renderMessages();else if(active==='topics')renderTopics();else if(active==='seminars'||active==='advisors')renderServices(active);else if(active==='resources'){pages.resources.replaceChildren(e('h1','','자료실'));const box=e('div');pages.resources.append(box);renderResources(box);}else if(active==='preferences')renderPreferences();window.createMisamoIcons?.();});}
  window.addEventListener('misamo:view',event=>{active=event.detail;if(active==='profile'){const suffix=location.hash.split('/').slice(1).join('/');if(suffix)try{profileId=decodeURIComponent(suffix);}catch{profileId=me;}}refresh();});
  window.addEventListener('misamo:community-change',event=>{const current=document.querySelector('.is-reading-target');if(current&&!C.posts().some(p=>p.id===current.dataset.postId))window.misamoNavigate?.('home');refresh();});window.addEventListener('misamo:post-rendered',refresh);window.addEventListener('misamo:post-published',refresh);
  window.MisamoCommunityUI={openProfile,openPost,openMessages,toast,refresh,dialog,search};
  refresh();
})();
