(function(){
'use strict';
const data=window.MisamoCommunity, ui=window.MisamoCommunityUI;if(!data||!ui)return;
function button(text,fn){const b=document.createElement('button');b.type='button';b.textContent=text;b.addEventListener('click',fn);return b;}
function icon(name){const node=document.createElement('i');node.dataset.lucide=name;node.setAttribute('aria-hidden','true');return node;}
function error(body,e){let p=body.querySelector('[data-action-error]');if(!p){p=document.createElement('p');p.dataset.actionError='';p.setAttribute('role','alert');body.append(p);}p.textContent=e?.message||'저장하지 못했습니다. 다시 시도해주세요.';}
function action(body,close,label,key,fn){const b=button(label,async()=>{try{await fn();close();}catch(e){error(body,e)}});b.dataset.postAction=key;body.append(b);}
function more(post){ui.dialog('게시글 메뉴',(body,close)=>{body.classList.add('community-post-menu');const s=data.state();const owned=post.authorId===(window.MisamoStore?.USER?.id||'demo-me');
if(owned){action(body,close,'글 수정','edit',()=>window.MisamoPosting.editPost(post.id));action(body,close,'글 삭제','delete',()=>confirmDelete(post));}
else {action(body,close,s.following.includes(post.authorId)?'팔로우 취소':'팔로우','follow',()=>data.toggleFollow(post.authorId));action(body,close,s.favorites.includes(post.authorId)?'즐겨찾기 해제':'작성자 즐겨찾기','favorite',()=>data.toggleFavorite(post.authorId));action(body,close,'이 게시글 숨기기','hide',()=>data.hidePost(post.id));action(body,close,'작성자 30일 숨기기','snooze',()=>data.snoozeAuthor(post.authorId,30));action(body,close,'작성자 차단','block',()=>data.blockAuthor(post.authorId));action(body,close,'게시글 신고','report',()=>report(post));}
action(body,close,s.subscriptions.includes(post.id)?'알림 구독 취소':'게시글 알림 구독','subscribe',()=>data.toggleSubscription(post.id));const note=document.createElement('p');note.textContent='개인 설정은 이 브라우저에 저장됩니다. 숨김·차단과 삭제한 글은 설정에서 복원할 수 있습니다.';body.append(note);});}
function confirmDelete(post){ui.dialog('게시글 삭제',(body,close)=>{const p=document.createElement('p');p.textContent='이 브라우저에서 글을 삭제할까요? 설정에서 복원할 수 있습니다.';body.append(p);action(body,close,'삭제 확인','confirm-delete',()=>data.deletePost(post.id));body.append(button('취소',close));});}
function report(post){ui.dialog('게시글 신고',(body,close)=>{const p=document.createElement('p');p.textContent='신고는 이 브라우저에만 기록되며 운영자에게 전송되지 않습니다.';const input=document.createElement('textarea');input.setAttribute('aria-label','신고 사유');body.append(p,input);action(body,close,'신고 기록 저장','confirm-report',()=>{if(!input.value.trim())throw Error('신고 사유를 입력해주세요.');data.reportPost(post.id,input.value.trim());});});}
function share(post){ui.dialog('게시글 공유',(body,close)=>{const url=new URL(window.location.href);url.search='';url.hash='post/'+encodeURIComponent(post.id);if(!['http:','https:'].includes(url.protocol))throw Error('웹 주소에서만 공유 링크를 만들 수 있습니다.');const p=document.createElement('p');p.textContent='직접 작성한 글은 이 브라우저에서만 열립니다. 공유 샘플은 다른 브라우저에서도 확인할 수 있습니다.';const input=document.createElement('input');input.readOnly=true;input.dataset.shareUrl='';input.setAttribute('aria-label','게시글 링크');input.value=url.href;body.append(p,input);body.append(button('링크 복사',async()=>{try{await navigator.clipboard.writeText(url.href);ui.toast('링크를 복사했습니다.');}catch(e){input.focus();input.select();error(body,Error('자동 복사를 사용할 수 없습니다. 선택된 링크를 직접 복사해주세요.'));}}));if(navigator.share)body.append(button('기기 공유',async()=>{try{await navigator.share({title:post.title,url:url.href});}catch(e){if(e.name!=='AbortError')error(body,e);}}));body.append(button('받는 사람 선택 · 로컬 메시지',()=>{close();ui.openMessages('',post.id);}));const embed=document.createElement('textarea');embed.readOnly=true;embed.setAttribute('aria-label','게시글 링크 HTML');const a=document.createElement('a');a.href=url.href;a.textContent=post.title||'게시글';a.rel='noopener noreferrer';embed.value=a.outerHTML;body.append(embed);});}
function gallery(card,post){const cover=card.querySelector('.post-image');if(!cover)return;const inline=new Set([...card.querySelectorAll('.post-rich-body img')].flatMap(i=>[i.dataset.imageId,i.src]));const images=(post.images||[]).filter(i=>!inline.has(i.id)&&!inline.has(i.src));card.querySelector('[data-cover-gallery]')?.remove();if(images.length<2)return;let index=Math.max(0,images.findIndex(i=>i.src===cover.src));const controls=document.createElement('div');controls.className='community-gallery-controls';controls.dataset.coverGallery='';const count=document.createElement('span');count.dataset.galleryCount='';function paint(){cover.src=images[index].src;cover.alt=images[index].alt||'첨부 이미지';count.textContent=`${index+1} / ${images.length}`;}const prev=button('이전 사진',()=>{index=(index-1+images.length)%images.length;paint()});prev.dataset.galleryPrev='';const next=button('다음 사진',()=>{index=(index+1)%images.length;paint()});next.dataset.galleryNext='';controls.append(prev,count,next);cover.after(controls);paint();}
const appliedEdits=new Map();
function hydrate(){document.querySelectorAll('.post-card[data-post-id]').forEach(card=>{const post=data.post(card.dataset.postId);if(!post)return;const edit=data.state().edits?.[post.id];if(edit){const revision=JSON.stringify(edit);if(appliedEdits.get(card)!==revision){appliedEdits.set(card,revision);window.MisamoPosting?.refreshPost(post);}}const head=card.querySelector('.post-head');if(!head)return;if(!head.querySelector('[data-community-profile]')){const name=head.querySelector('strong');if(name){const a=document.createElement('a');a.href='#profile/'+encodeURIComponent(post.authorId);a.dataset.communityProfile='';a.textContent=name.textContent;a.addEventListener('click',e=>{e.preventDefault();ui.openProfile(post.authorId)});name.replaceChildren(a);}}
const profileLink=head.querySelector('[data-community-profile]');if(profileLink)profileLink.textContent=data.profile?.(post.authorId)?.name||post.author||profileLink.textContent;
if(!head.querySelector('[data-community-more]')){const b=head.querySelector('button[aria-label="더보기"]')||button('⋯',()=>{});b.classList.add('icon-button','flat');b.replaceChildren(icon('ellipsis'));b.dataset.communityMore='';b.setAttribute('aria-label','게시글 더보기');b.setAttribute('aria-haspopup','dialog');b.addEventListener('click',()=>{const current=data.post(card.dataset.postId);if(current)more(current)});if(!b.parentNode)head.append(b);}
const footer=card.querySelector('.post-actions');footer?.querySelectorAll('button').forEach(b=>{if(!b.hasAttribute('data-community-share')&&b.querySelector('[data-lucide="send"],svg.lucide-send'))b.remove();});if(footer&&!footer.querySelector('[data-community-share]')){const b=button('공유',()=>share(data.post(card.dataset.postId)||post));b.className='action-button';b.dataset.communityShare='';b.setAttribute('aria-label','공유');b.setAttribute('aria-haspopup','dialog');b.title='공유';b.replaceChildren(icon('share-2'));footer.append(b);}gallery(card,post);});window.createMisamoIcons?.();}
window.MisamoCommunityPosts={hydrate,share};hydrate();window.addEventListener('misamo:post-rendered',hydrate);window.addEventListener('misamo:community-change',hydrate);
})();
